name: Validate Pull Request Metadata

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize
      - edited

env:
  LABELS: ${{ join( github.event.pull_request.labels.*.name, ' ' ) }}

jobs:
  check-type-label:
    name: Check label for type
    runs-on: ubuntu-latest
    steps:
      - if: contains( env.LABELS, 'Build' ) == false && contains( env.LABELS, 'Documentation' ) == false && contains( env.LABELS, 'Bug' ) == false && contains( env.LABELS, 'Dependencies' ) == false && contains( env.LABELS, 'Enhancement' ) == false && contains( env.LABELS, 'New-Feature' ) == false
        run: exit 1
  check-product-label:
    name: Check label for product
    runs-on: ubuntu-latest
    steps:
      - if: contains( env.LABELS, 'Open source only' ) == false && contains( env.LABELS, 'Azure API for FHIR' ) == false && contains( env.LABELS, 'Azure Healthcare APIs' ) == false
        run: exit 1
  check-milestone:
    name: Check milestone
    runs-on: ubuntu-latest
    steps:
      - if: github.event.pull_request.milestone == null
        run: exit 1